In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import sympy
import pandas as pd

from IPython.display import Image

# Importación

from sympy import init_session
init_session(use_latex=True)

IPython console for SymPy 1.3 (Python 2.7.17-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at http://docs.sympy.org/1.3/



# Geometria de los Elementos

In [2]:
### Elementos Individuales

def crear_elemento(Id, E, A, I, xi, yi, xf, yf,             
                   giro_i, giro_f, desy_i, desy_f, desx_i, desx_f,
                   TC, W):
    
    ID = Id
    l = ((xf - xi) ** 2 + (yf - yi) ** 2) ** 0.5
    Cx = (xf - xi) / l
    Cy = (yf - yi) / l
    GDL = [giro_i, giro_f, desx_i, desx_f, desy_i, desy_f]
    
    if TC == 'Nada':
        
        Me_i = 0
        Me_f = 0
        Ve_i = 0 
        Ve_f = 0
    
    elif TC == 'Puntual1':
        
        Me_i = (W * l) / 8.0
        Me_f = - (W * l) / 8.0
        Ve_i = (W) / 2.0
        Ve_f = (W) / 2.0
    
    elif TC == 'Distr':

        Me_i = (W * l ** 2) / 12.0
        Me_f = - (W * l ** 2) / 12.0
        Ve_i = (W * l) / 2.0
        Ve_f = (W * l) / 2.0

    return ID, l, Cx, Cy, A, E, I, GDL, Me_i, Me_f, Ve_i, Ve_f 

### Introducir Datos de los Elementos

In [3]:
# Propiedades material
e = 20000 * (10 ** 3) ### [KN/m^2]
ac =  0.50 * 0.50 ### [m^2]
av =  0.30 * 0.40 ### [m^2]
ic = (0.5 * (0.5 ** 3)) / 12.0 ### [m^4]
iv = (0.3 * (0.4 ** 3)) / 12.0 ### [m^4]

In [4]:
Elementos = 6

Elemento1 = crear_elemento(Id = '01', E = e, A = ac, I = ic, xi = 0.0, yi = 0.0, xf = 0.0, yf = 3.0,
                           giro_i = 0, giro_f = 1, desx_i = 0, desx_f = 5, desy_i = 0, desy_f = 0,
                           TC = 'Nada', W = 0)

Elemento2 = crear_elemento(Id = '02', E = e, A = ac, I = ic, xi = 6.0, yi = 0.0, xf = 6.0, yf = 3.0,
                           giro_i = 0, giro_f = 2, desx_i = 0, desx_f = 5, desy_i = 0, desy_f = 0,
                           TC = 'Nada', W = 0)

Elemento3 = crear_elemento(Id = '03', E = e, A = ac, I = ic, xi = 0.0, yi = 3.0, xf = 0.0, yf = 5.5,
                           giro_i = 1, giro_f = 3, desx_i = 5, desx_f = 6, desy_i = 0, desy_f = 0,
                           TC = 'Nada', W = 0)

Elemento4 = crear_elemento(Id = '04', E = e, A = ac, I = ic, xi = 6.0, yi = 3.0, xf = 6.0, yf = 5.5,
                           giro_i = 2, giro_f = 4, desx_i = 5, desx_f = 6, desy_i = 0, desy_f = 0,
                           TC = 'Nada', W = 0)

Elemento5 = crear_elemento(Id = '05', E = e, A = av, I = iv, xi = 0.0, yi = 3.0, xf = 6.0, yf = 3.0,
                           giro_i = 1, giro_f = 2, desx_i = 0, desx_f = 0, desy_i = 0, desy_f = 0,
                           TC = 'Distr', W = 80)

Elemento6 = crear_elemento(Id = '06', E = e, A = av, I = iv, xi = 0.0, yi = 5.5, xf = 6.0, yf = 5.5,
                           giro_i = 3, giro_f = 4, desx_i = 0, desx_f = 0, desy_i = 0, desy_f = 0,
                           TC = 'Distr', W = 80)

El = [None] * Elementos
for i in np.arange(0, Elementos):
    exec 'El[%s] = %s' % (i, 'Elemento' + str(i + 1))
    
Columns = ['ID', 'L', 'CX', 'CY', 'A', 'E', 'I', 'GDL', 'Me_i', 'Me_f', 'Ve_i', 'Ve_f']
Tabla_Datos = pd.DataFrame(data = El, index = np.arange(0, Elementos), columns = Columns)
Tabla_Datos

ID    L   CX   CY     A         E         I                 GDL   Me_i  \
0  01  3.0  0.0  1.0  0.25  20000000  0.005208  [0, 1, 0, 5, 0, 0]    0.0   
1  02  3.0  0.0  1.0  0.25  20000000  0.005208  [0, 2, 0, 5, 0, 0]    0.0   
2  03  2.5  0.0  1.0  0.25  20000000  0.005208  [1, 3, 5, 6, 0, 0]    0.0   
3  04  2.5  0.0  1.0  0.25  20000000  0.005208  [2, 4, 5, 6, 0, 0]    0.0   
4  05  6.0  1.0  0.0  0.12  20000000  0.001600  [1, 2, 0, 0, 0, 0]  240.0   
5  06  6.0  1.0  0.0  0.12  20000000  0.001600  [3, 4, 0, 0, 0, 0]  240.0   

    Me_f   Ve_i   Ve_f  
0    0.0    0.0    0.0  
1    0.0    0.0    0.0  
2    0.0    0.0    0.0  
3    0.0    0.0    0.0  
4 -240.0  240.0  240.0  
5 -240.0  240.0  240.0

# Matriz de Rigidez

### Matriz de la Rigidez en Coordenadas Locales

In [5]:
def matriz_local(L, A, E, I):
    
    K11 = (4 * E * I) / L 
    K21 = (2 * E * I) / L
    K31 = (K11 + K21) / L
    K41 = -(K11 + K21) / L
    K51 = 0.0
    K61 = 0.0
    
    K12 = K21
    K22 = (4 * E * I) / L
    K32 = (K22 + K21) / L
    K42 = -(K22 + K21) / L
    K52 = 0.0
    K62 = 0.0
    
    K13 = K31
    K23 = K32
    K33 = (K11 + K22 + 2 * K21) / (L ** 2) 
    K43 = -(K11 + K22 + 2 * K21) / (L ** 2) 
    K53 = 0.0
    K63 = 0.0
    
    K14 = K41
    K24 = K42
    K34 = K43 
    K44 = (K11 + K22 + 2 * K21) / (L ** 2)
    K54 = 0.0
    K64 = 0.0
    
    K15 = K51
    K25 = K52
    K35 = K53 
    K45 = K54
    K55 = A * E / L 
    K65 = - A * E / L
    
    K16 = K61
    K26 = K62
    K36 = K63 
    K46 = K64
    K56 = K65 
    K66 = A * E / L
    
    k = [[K11, K21, K31, K41, K51, K61],[K12, K22, K32, K42, K52, K62],[K13, K23, K33, K43, K53, K63],
        [K14, K24, K34, K44, K54, K64],[K15, K25, K35, K45, K55, K65],[K16, K26, K36, K46, K56, K66]]
    
    matriz = np.matrix(np.round(k,2))
        
    return matriz

In [6]:
Matriz_local = [None] * len(Tabla_Datos)

for i in np.arange(len(Tabla_Datos)):

    L = Tabla_Datos['L'][i]
    A = Tabla_Datos['A'][i]
    E = Tabla_Datos['E'][i]
    I = Tabla_Datos['I'][i]

    Matriz_local[i] = matriz_local(L, A, E, I)
    
for i in np.arange(len(Matriz_local)):
    
    print 'Matriz del Elemento ' + Tabla_Datos['ID'][i]
    print Matriz_local[i]
    print '\n'

Matriz del Elemento 01
[[  138888.89    69444.44    69444.44   -69444.44        0.          0.  ]
 [   69444.44   138888.89    69444.44   -69444.44        0.          0.  ]
 [   69444.44    69444.44    46296.3    -46296.3         0.          0.  ]
 [  -69444.44   -69444.44   -46296.3     46296.3         0.          0.  ]
 [       0.          0.          0.          0.    1666666.67 -1666666.67]
 [       0.          0.          0.          0.   -1666666.67  1666666.67]]


Matriz del Elemento 02
[[  138888.89    69444.44    69444.44   -69444.44        0.          0.  ]
 [   69444.44   138888.89    69444.44   -69444.44        0.          0.  ]
 [   69444.44    69444.44    46296.3    -46296.3         0.          0.  ]
 [  -69444.44   -69444.44   -46296.3     46296.3         0.          0.  ]
 [       0.          0.          0.          0.    1666666.67 -1666666.67]
 [       0.          0.          0.          0.   -1666666.67  1666666.67]]


Matriz del Elemento 03
[[  166666.67    83333.33

### Matriz de Transformación

In [7]:
def matriz_T(CX, CY):
    
    T11 = 1.0 
    T21 = 0.0
    T31 = 0.0
    T41 = 0.0
    T51 = 0.0
    T61 = 0.0
    
    T12 = 0.0
    T22 = 1.0
    T32 = 0.0
    T42 = 0.0
    T52 = 0.0
    T62 = 0.0
    
    T13 = 0.0
    T23 = 0.0
    T33 = -1.0 * CY 
    T43 = 0.0 
    T53 = CX
    T63 = 0.0
    
    T14 = 0.0
    T24 = 0.0
    T34 = 0.0
    T44 = -1.0 * CY
    T54 = 0.0
    T64 = CX
    
    T15 = 0.0
    T25 = 0.0
    T35 = CX 
    T45 = 0.0
    T55 = CY 
    T65 = 0.0
    
    T16 = 0.0
    T26 = 0.0
    T36 = 0.0
    T46 = CX
    T56 = 0.0 
    T66 = CY
    
    T = [[T11, T21, T31, T41, T51, T61], [T12, T22, T32, T42, T52, T62], [T13, T23, T33, T43, T53, T63],
         [T14, T24, T34, T44, T54, T64], [T15, T25, T35, T45, T55, T65], [T16, T26, T36, T46, T56, T66]]
    
    matriz = np.matrix(np.round(T,4))
        
    return matriz

In [8]:
Matriz_T = [None] * len(Tabla_Datos)

for i in np.arange(len(Tabla_Datos)):

    CX = Tabla_Datos['CX'][i]
    CY = Tabla_Datos['CY'][i]
    
    Matriz_T[i] = matriz_T(CX,CY)
    
for i in np.arange(len(Matriz_T)):
    
    print u'Matriz de Transformación ' + Tabla_Datos['ID'][i]
    print Matriz_T[i]
    print '\n'

Matriz de Transformación 01
[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]


Matriz de Transformación 02
[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]


Matriz de Transformación 03
[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]


Matriz de Transformación 04
[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]


Matriz de Transformación 05
[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0. -0.  0.  1.  0.]
 [ 0.  0.  0. -0.  0.  1.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]]


Matriz de Transformación 06
[[ 1.  

### Matriz de la Rigidez en Coordenadas Globales

In [9]:
Matriz_global = [None] * len(Tabla_Datos)

for i in np.arange(len(Tabla_Datos)):

    Matriz_global[i] = Matriz_T[i] * Matriz_local[i] * Matriz_T[i]
    
    print u'Matriz del Elemento ' + Tabla_Datos['ID'][i] + ' (Globales)'
    print Matriz_global[i]
    print '\n'

Matriz del Elemento 01 (Globales)
[[  138888.89    69444.44   -69444.44    69444.44        0.          0.  ]
 [   69444.44   138888.89   -69444.44    69444.44        0.          0.  ]
 [  -69444.44   -69444.44    46296.3    -46296.3         0.          0.  ]
 [   69444.44    69444.44   -46296.3     46296.3         0.          0.  ]
 [       0.          0.          0.          0.    1666666.67 -1666666.67]
 [       0.          0.          0.          0.   -1666666.67  1666666.67]]


Matriz del Elemento 02 (Globales)
[[  138888.89    69444.44   -69444.44    69444.44        0.          0.  ]
 [   69444.44   138888.89   -69444.44    69444.44        0.          0.  ]
 [  -69444.44   -69444.44    46296.3    -46296.3         0.          0.  ]
 [   69444.44    69444.44   -46296.3     46296.3         0.          0.  ]
 [       0.          0.          0.          0.    1666666.67 -1666666.67]
 [       0.          0.          0.          0.   -1666666.67  1666666.67]]


Matriz del Elemento 03 (Gl

### Matriz de Rigidez de la Estructura (GDL)

In [10]:
N_GDL = 6
Matriz_GDL = [[None] * N_GDL for i in range(N_GDL)]

N = np.arange(1, N_GDL + 1)

for i in np.arange(len(N)):
    for j in np.arange(len(N)):
        Matriz_GDL[i][j] = str(N[i]) + str(N[j])

Matriz_GDL = np.matrix(Matriz_GDL)
Matriz_GDL

matrix([['11', '12', '13', '14', '15', '16'],
        ['21', '22', '23', '24', '25', '26'],
        ['31', '32', '33', '34', '35', '36'],
        ['41', '42', '43', '44', '45', '46'],
        ['51', '52', '53', '54', '55', '56'],
        ['61', '62', '63', '64', '65', '66']], dtype='|S2')

In [11]:
gdl_sel = []
rig_sel = []

for e in np.arange(len(Tabla_Datos)):
    
    for g in Matriz_GDL.flat:

        cuenta = -1
        for i in Tabla_Datos['GDL'][e]:

            for j in Tabla_Datos['GDL'][e]:

                cuenta = cuenta + 1

                if str(i) + str(j) == g:

#                     print str(i) + str(j), cuenta, Matriz_global[e].flat[cuenta]
                    
                    gdl_sel.append(Matriz_global[e].flat[cuenta])
                    rig_sel.append(str(i) + str(j))
            
Matriz_Ppal = np.matrix([np.zeros(N_GDL) for i in range(N_GDL)])
Matriz_Ppal

for g in np.arange(len(np.matrix(Matriz_GDL).A1)):
        
    for i in np.arange(len(rig_sel)):
        
        if Matriz_GDL.flat[g] == rig_sel[i]:
                    
            Matriz_Ppal.flat[g] = Matriz_Ppal.flat[g] + gdl_sel[i]  
            
# Matriz_K = Matrix(Matriz_Ppal)
# Matriz_Kprint 'Resultados de los Mu_global'

In [12]:
Columns_GDL = ['$\Theta_1$', '$\Theta_2$', '$\Theta_3$', '$\Theta_4$',
               '$\Delta_1$', '$\Delta_2$']

Matriz_GDL = pd.DataFrame(data = Matriz_Ppal,index = Columns_GDL, columns = Columns_GDL)
Matriz_GDL

$\Theta_1$  $\Theta_2$  $\Theta_3$  $\Theta_4$  $\Delta_1$  \
$\Theta_1$   326888.89    10666.67    83333.33        0.00   -30555.56   
$\Theta_2$    10666.67   326888.89        0.00    83333.33   -30555.56   
$\Theta_3$    83333.33        0.00   188000.00    10666.67  -100000.00   
$\Theta_4$        0.00    83333.33    10666.67   188000.00  -100000.00   
$\Delta_1$   -30555.56   -30555.56  -100000.00  -100000.00   252592.60   
$\Delta_2$   100000.00   100000.00   100000.00   100000.00  -160000.00   

            $\Delta_2$  
$\Theta_1$    100000.0  
$\Theta_2$    100000.0  
$\Theta_3$    100000.0  
$\Theta_4$    100000.0  
$\Delta_1$   -160000.0  
$\Delta_2$    160000.0

# Vector de Cargas

In [13]:
TD = Tabla_Datos.loc()

### Cargas en los elementos
P_Elementos = np.matrix([[0.0] * N_GDL]).T

### Giros
P_Elementos[0] = TD[4]['Me_i']
P_Elementos[1] = TD[4]['Me_f']
P_Elementos[2] = TD[5]['Me_i']
P_Elementos[3] = TD[5]['Me_f']

### Desplazamientos Horizontales
P_Elementos[4] = 0
P_Elementos[5] = 0

### Cargas en nudos
P_Nudos = np.matrix([[0.0] * N_GDL]).T

P_Nudos[4] = 120
P_Nudos[5] = 220

### Vector de Cargas

P = P_Nudos - P_Elementos

Vector_P = pd.DataFrame(data = P,index = Columns_GDL, columns = ['Vector_P'])
Vector_P

Vector_P
$\Theta_1$    -240.0
$\Theta_2$     240.0
$\Theta_3$    -240.0
$\Theta_4$     240.0
$\Delta_1$     120.0
$\Delta_2$     220.0

# Vector Respuesta

In [14]:
### Calculo de la Matriz Inversa
Inv_Matriz = Matriz_Ppal.I

### Calculo de la respuesta GDL
R = Inv_Matriz * P

Vector_R = pd.DataFrame(data = R,index = Columns_GDL, columns = ['Vector_R'])
Vector_R

Vector_R
$\Theta_1$ -0.006003
$\Theta_2$ -0.005085
$\Theta_3$ -0.006140
$\Theta_4$ -0.003865
$\Delta_1$  0.011988
$\Delta_2$  0.026547

### Grados de Libertad de Cada Elemento

In [15]:
GLs = [None] * len(Tabla_Datos)
for i in np.arange(len(Tabla_Datos)):
    
    Datos = Tabla_Datos['GDL'][i]
    GL = np.matrix([[0.0] * len(Datos)]).T
    for j in np.arange(len(Datos)):
        
        if Datos[j]-1 == -1:
            GL[j] = 0
        
        else:
            GL[j] = R[Datos[j]-1]

    GLs[i] = GL

Me_global = [None] * len(Tabla_Datos)
for i in np.arange(len(Tabla_Datos)):
    
    Datos = Tabla_Datos['GDL'][i]
    Me_gl = np.matrix([[0.0] * len(Datos)]).T
    
    Me_gl[0] = Tabla_Datos['Me_i'][i]
    Me_gl[1] = Tabla_Datos['Me_f'][i]
    Me_gl[4] = Tabla_Datos['Ve_i'][i]
    Me_gl[5] = Tabla_Datos['Ve_f'][i]
    
    Me_global[i] = Me_gl
    
Mu_global = [None] * len(Tabla_Datos)
for i in np.arange(len(Tabla_Datos)):
    
    Mu_global[i] = Matriz_global[i] * GLs[i]

In [16]:
##### Rotulos de las tablas

columns_el = []
for i in np.arange(0, Elementos):
    col_el = Tabla_Datos['ID'][i]
    columns_el.append(col_el)

index_GLs = ['$M_i$', '$M_f$', '$X_i$', '$X_f$', '$Y_i$', '$Y_f$']

In [17]:
print 'Resultados de los GL'

array_GLs = np.squeeze(np.asarray(GLs))
df_Gls = pd.DataFrame(data = array_GLs.transpose(), index=index_GLs, columns=columns_el)
df_Gls

Resultados de los GL


01        02        03        04        05        06
$M_i$  0.000000  0.000000 -0.006003 -0.005085 -0.006003 -0.006140
$M_f$ -0.006003 -0.005085 -0.006140 -0.003865 -0.005085 -0.003865
$X_i$  0.000000  0.000000  0.011988  0.011988  0.000000  0.000000
$X_f$  0.011988  0.011988  0.026547  0.026547  0.000000  0.000000
$Y_i$  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
$Y_f$  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

In [18]:
print 'Resultados de los Me_global'

array_Me_global = np.squeeze(np.asarray(Me_global))
df_Me_global = pd.DataFrame(data = array_Me_global.transpose(), index=index_GLs, columns=columns_el)
df_Me_global

Resultados de los Me_global


01   02   03   04     05     06
$M_i$  0.0  0.0  0.0  0.0  240.0  240.0
$M_f$  0.0  0.0  0.0  0.0 -240.0 -240.0
$X_i$  0.0  0.0  0.0  0.0    0.0    0.0
$X_f$  0.0  0.0  0.0  0.0    0.0    0.0
$Y_i$  0.0  0.0  0.0  0.0  240.0  240.0
$Y_f$  0.0  0.0  0.0  0.0  240.0  240.0

In [19]:
print 'Resultados de los Mu_global'

array_Mu_global = np.squeeze(np.asarray(Mu_global))
df_Mu_global = pd.DataFrame(data = array_Mu_global.transpose(), index=index_GLs, columns=columns_el)
df_Mu_global

Resultados de los Mu_global


01          02         03          04          05          06
$M_i$  415.621129  479.394521 -56.405356  286.252263 -182.313127 -172.211033
$M_f$   -1.281517  126.265276 -67.788967  387.942060 -172.517539 -147.942060
$X_i$ -138.113304 -201.886696  49.677729 -269.677729    0.000000    0.000000
$X_f$  138.113304  201.886696 -49.677729  269.677729    0.000000    0.000000
$Y_i$    0.000000    0.000000   0.000000    0.000000  -59.138407  -53.358816
$Y_f$    0.000000    0.000000   0.000000    0.000000   59.138407   53.358816

# Cargas Finales

In [20]:
M_final = [None] * len(Tabla_Datos)
for i in np.arange(len(Tabla_Datos)):
    
    M_final[i] = Me_global[i] + Mu_global[i]

In [21]:
print 'Resultados de las M_final'

array_M_final = np.round(np.squeeze(np.asarray(M_final)),4)
df_M_final = pd.DataFrame(data = array_M_final.transpose(), index=index_GLs, columns=columns_el)
df_M_final

Resultados de las M_final


01        02       03        04        05        06
$M_i$  415.6211  479.3945 -56.4054  286.2523   57.6869   67.7890
$M_f$   -1.2815  126.2653 -67.7890  387.9421 -412.5175 -387.9421
$X_i$ -138.1133 -201.8867  49.6777 -269.6777    0.0000    0.0000
$X_f$  138.1133  201.8867 -49.6777  269.6777    0.0000    0.0000
$Y_i$    0.0000    0.0000   0.0000    0.0000  180.8616  186.6412
$Y_f$    0.0000    0.0000   0.0000    0.0000  299.1384  293.3588

### Momentos maximos en el intermedio de los elementos

In [22]:
def moment_max_dist(M_i, M_f, V_i, V_f, L, W):
    
    x = (V_i * L) / (V_i + V_f)
    
    M_max = - M_i + V_i * x - (W * (x ** 2) / 2.0)
    
    return np.round(x,4), np.round(M_max,4)

In [23]:
x_05, Mmax_05 = moment_max_dist(M_i = df_M_final['05']['$M_i$'], M_f = df_M_final['05']['$M_f$'], 
                                V_i = df_M_final['05']['$Y_i$'], V_f = df_M_final['05']['$Y_f$'], 
                                L = Tabla_Datos['L'][4], W = 80)

x_06, Mmax_06 = moment_max_dist(M_i = df_M_final['06']['$M_i$'], M_f = df_M_final['06']['$M_f$'], 
                                V_i = df_M_final['06']['$Y_i$'], V_f = df_M_final['06']['$Y_f$'], 
                                L = Tabla_Datos['L'][5], W = 80)

print 'Elemento 05'
print u'El momento interior máximo es ' + str(Mmax_05) + 'KN y ocurre a ' + str(x_05) + ' m del apoyo \n' 

print 'Elemento 06'
print u'El momento interior máximo es ' + str(Mmax_06) + 'KN y ocurre a ' + str(x_06) + ' m del apoyo \n'

Elemento 05
El momento interior máximo es 146.7563KN y ocurre a 2.2608 m del apoyo 

Elemento 06
El momento interior máximo es 149.9294KN y ocurre a 2.333 m del apoyo 

